apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sunilsabnis/scheduler-app:dev-frontend
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
