// all types send by redux actions and recognized by redux reducers

// calendar ops
export const NEW_DAYS = "NEW_DAYS";

// group api
export const CREATE_GROUP_PENDING = "CREATE_GROUP_PENDING";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";

export const SEND_INVITE_PENDING = "SEND_INVITE_PENDING";
export const SEND_INVITE_SUCCESS = "SEND_INVITE_SUCCESS";
export const SEND_INVITE_ERROR = "SEND_INVITE_PENDING";

export const ACCEPT_INVITE_PENDING = "ACCEPT_INVITE_PENDING";
export const ACCEPT_INVITE_SUCCESS = "ACCEPT_INVITE_SUCCESS";
export const ACCEPT_INVITE_ERROR = "ACCEPT_INVITE_PENDING";

export const LEAVE_GROUP_PENDING = "LEAVE_GROUP_PENDING";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_ERROR = "LEAVE_GROUP_PENDING";

export const DECLINE_INVITE_PENDING = "DECLINE_INVITE_PENDING";
export const DECLINE_INVITE_SUCCESS = "DECLINE_INVITE_SUCCESS";
export const DECLINE_INVITE_ERROR = "DECLINE_INVITE_PENDING";

export const GET_GROUPS_PENDING = "GET_GROUPS_PENDING";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_ERROR = "GET_GROUPS_PENDING";

export const GET_INVITES_PENDING = "GET_INVITES_PENDING";
export const GET_INVITES_SUCCESS = "GET_INVITES_SUCCESS";
export const GET_INVITES_ERROR = "GET_INVITES_PENDING";

export const RENAME_GROUP_PENDING = "RENAME_GROUP_PENDING";
export const RENAME_GROUP_SUCCESS = "RENAME_GROUP_SUCCESS";
export const RENAME_GROUP_ERROR = "RENAME_GROUP_PENDING";
